In [1]:
import numpy as np
import pandas as pd
from SERGIO.sergio import sergio
import random
import networkx as nx
from pyvis.network import Network
import graphviz
from scipy import stats

In [2]:
# Based on: De-noised_100G_3T_300cPerT_dynamics_8_DS8
# (100 Genes, 3 Cell Types, 300 Cells Per Type, 900 Total Cells)

In [3]:
sim = sergio(number_genes=100, number_bins = 3, number_sc = 300, noise_params = 1, decays=0.8, sampling_state=15, noise_type='dpd')
sim.build_graph(input_file_taregts ='data_sets/De-noised_100G_3T_300cPerT_dynamics_8_DS8/Interaction_cID_8_1.txt', 
                input_file_regs='data_sets/De-noised_100G_3T_300cPerT_dynamics_8_DS8/Regs_cID_8.txt', shared_coop_state=2)
sim.simulate()
expr = sim.getExpressions()
expr_clean = np.concatenate(expr, axis = 1)

Start simulating new level
There are 3 genes to simulate in this layer
Done with current level
Start simulating new level
There are 7 genes to simulate in this layer
Done with current level
Start simulating new level
There are 90 genes to simulate in this layer
Done with current level


In [6]:
expr_O = sim.outlier_effect(expr, outlier_prob = 0.01, mean = 0.8, scale = 1)
libFactor, expr_O_L = sim.lib_size_effect(expr_O, mean = 4.6, scale = 0.4)
binary_ind = sim.dropout_indicator(expr_O_L, shape = 6.5, percentile = 0)
expr_O_L_D = np.multiply(binary_ind, expr_O_L)
count_matrix = sim.convert_to_UMIcounts(expr_O_L_D)
count_matrix = np.concatenate(count_matrix, axis = 1)
print(count_matrix)
np.save('FeaturesSet1.npy', count_matrix.T)

[[2 0 2 ... 1 0 2]
 [0 0 1 ... 0 0 0]
 [1 2 1 ... 1 1 1]
 ...
 [2 1 2 ... 2 2 0]
 [0 1 3 ... 0 4 1]
 [0 4 1 ... 2 0 2]]


In [7]:
sz = count_matrix.shape
for i in range(0, sz[0]):
    curr = count_matrix[i, :]
    ct = 0
    for j in range(0, sz[1]):
        if curr[j] != 0:
            ct += 1
    if ct == sz[1]:
        print(i)

In [8]:
sz = count_matrix.shape
for i in range(0, sz[1]):
    curr = count_matrix[:, i]
    ct = 0
    for j in range(0, sz[0]):
        if curr[j] != 0:
            ct += 1
    if ct == sz[0]:
        print(i)

In [9]:
sim = sergio(number_genes=100, number_bins = 3, number_sc = 300, noise_params = 1, decays=0.8, sampling_state=15, noise_type='dpd')
sim.build_graph(input_file_taregts ='data_sets/De-noised_100G_3T_300cPerT_dynamics_8_DS8/Interaction_cID_8_2.txt', 
                input_file_regs='data_sets/De-noised_100G_3T_300cPerT_dynamics_8_DS8/Regs_cID_8.txt', shared_coop_state=2)
sim.simulate()
expr = sim.getExpressions()
expr_clean = np.concatenate(expr, axis = 1)

Start simulating new level
There are 3 genes to simulate in this layer
Done with current level
Start simulating new level
There are 7 genes to simulate in this layer
Done with current level
Start simulating new level
There are 90 genes to simulate in this layer
Done with current level


In [10]:
expr_O = sim.outlier_effect(expr, outlier_prob = 0.01, mean = 0.8, scale = 1)
libFactor, expr_O_L = sim.lib_size_effect(expr_O, mean = 4.6, scale = 0.4)
binary_ind = sim.dropout_indicator(expr_O_L, shape = 6.5, percentile = 0)
expr_O_L_D = np.multiply(binary_ind, expr_O_L)
count_matrix = sim.convert_to_UMIcounts(expr_O_L_D)
count_matrix = np.concatenate(count_matrix, axis = 1)
print(count_matrix)
np.save('FeaturesSet2.npy', count_matrix.T)

[[1 0 0 ... 3 0 1]
 [0 0 1 ... 0 1 0]
 [2 0 1 ... 1 3 0]
 ...
 [2 1 1 ... 0 1 4]
 [0 0 0 ... 0 0 0]
 [0 0 3 ... 0 1 0]]


In [11]:
sz = count_matrix.shape
for i in range(0, sz[0]):
    curr = count_matrix[i, :]
    ct = 0
    for j in range(0, sz[1]):
        if curr[j] != 0:
            ct += 1
    if ct == sz[1]:
        print(i)

In [12]:
sz = count_matrix.shape
for i in range(0, sz[1]):
    curr = count_matrix[:, i]
    ct = 0
    for j in range(0, sz[0]):
        if curr[j] != 0:
            ct += 1
    if ct == sz[0]:
        print(i)

In [59]:
df1 = pd.read_csv('data_sets/De-noised_100G_3T_300cPerT_dynamics_8_DS8/gt_GRN.csv')
l1 = list(df1['P1'])
l2 = list(df1['P2'])
np.save('data_sets/De-noised_100G_3T_300cPerT_dynamics_8_DS8/gt_GRN1.npy', [l1, l2])
df2 = pd.read_csv('data_sets/De-noised_100G_3T_300cPerT_dynamics_8_DS8/gt_GRN2.csv')
l1 = list(df2['P1'])
l2 = list(df2['P2'])
np.save('data_sets/De-noised_100G_3T_300cPerT_dynamics_8_DS8/gt_GRN2.npy', [l1, l2])

In [61]:
gt1 = np.load('data_sets/De-noised_100G_3T_300cPerT_dynamics_8_DS8/gt_GRN1.npy')
gt2 = np.load('data_sets/De-noised_100G_3T_300cPerT_dynamics_8_DS8/gt_GRN2.npy')
print(gt1.shape, gt2.shape)
s = set()
lst1 = []
lst2 = []
for i in range(0, gt1.shape[1]):
    p1 = gt1[0, i]
    p2 = gt1[1, i]
    if (p1, p2) not in s:
        lst1.append(p1)
        lst2.append(p2)
        s.add((p1, p2))
for i in range(0, gt2.shape[1]):
    p1 = gt2[0, i]
    p2 = gt2[1, i]
    if (p1, p2) not in s:
        lst1.append(p2)
        lst2.append(p2)
        s.add((p1, p2))
print(len(lst1), len(lst2), len(s))

(2, 137) (2, 137)
251 251 251


In [63]:
np.save('FullEdgeIndex.npy', [lst1, lst2])
print(len(lst1))

251


In [76]:
def create_comp_graph(feat, corr, edge1, edge2):
    '''Get a graph based on highly correlated features (feat) and given correlation (corr).'''
    X = feat.T # Transpose feature matrix to be gene x cell --> we want highly correlated GENES not cells/patients :)
    s_l = []
    d_l = []
    s1 = set()
    for i in range(0, edge1.shape[1]):
        p1 = edge1[0, i]
        p2 = edge1[1, i]
        s1.add((p1, p2))
    s2 = set()
    shared = set()
    for i in range(0, edge2.shape[1]):
        p1 = edge2[0, i]
        p2 = edge2[1, i]
        if (p1, p2) in s1:
            shared.add((p1, p2))
        else:
            s2.add((p1, p2))
    s1 = set()
    for i in range(0, edge1.shape[1]):
        p1 = edge1[0, i]
        p2 = edge1[1, i]
        if (p1, p2) not in shared:
            s1.add((p1, p2))
    ct1 = 0
    ct2 = 0
    share = 0
    for i in range(X.shape[0]):
        for j in range(X.shape[0]):
            if i != j:
                res = abs(stats.pearsonr(X[i, :], X[j, :])[0]) # Get the correlation between each gene
                if res >= corr:
                    s_l.append(i)
                    d_l.append(j)
                    if (i, j) in s1:
                        ct1 += 1
                    if (i, j) in s2:
                        ct2 += 1
                    if (i, j) in shared:
                        share += 1
    print(f"Number of Edges: {len(s_l)}") # Prints # of edges so you can make sure it isn't empty/too large
    print(ct1, ct2, share)
    edge_index = np.array([s_l, d_l]) # Convert to array
    return edge_index # Return edge index

In [78]:
a = np.load('FeaturesSet1.npy')
b = np.load('FeaturesSet2.npy')
features = np.concatenate((a, b), axis=0)
res = create_comp_graph(features, 0.15, gt1, gt2) # Generate correlation graph based on correlation
filename = 'CorrelationEdgeIndex'
np.save(f'{filename}.npy', res) # Save edge index as .npy file to run

Number of Edges: 2238
20 28 13


In [80]:
res = create_comp_graph(features, 0, gt1, gt2)

Number of Edges: 9900
114 114 23


In [18]:
a.shape

(900, 100)

In [19]:
b.shape

(900, 100)

In [20]:
ys = []
for i in range(0, 300):
    ys.append(0)
for i in range(0, 300):
    ys.append(1)
for i in range(0, 300):
    ys.append(2)
np.save('Y1.npy', ys)
np.save('Y2.npy', ys)

In [21]:
# df = pd.read_csv('data_sets/De-noised_100G_3T_300cPerT_dynamics_8_DS8/gt_GRN.csv')
# regs = [90, 79, 5, 1, 18, 9]
# g = Network(notebook=True, directed=True)
# ei1 = list(df['P1'])
# ei2 = list(df['P2'])
# b1 = []
# b2 = []
# n = []
# c = []
# for i in range(len(ei1)):
#     b1.append(ei1[i])
#     b2.append(ei2[i])
# u1 = np.unique(b1)
# u2 = np.unique(b2)
# for i in u1:
#     if i not in n:
#         n.append(i)
#         if i not in regs:
#             c.append('black')
#         else:
#             c.append('pink')
# for i in u2:
#     if i not in n:
#         n.append(i)
#         if i not in regs:
#             c.append('black')
#         else:
#             c.append('pink')
# g.add_nodes(n, color=c)
# for i in range(0, len(b1)):
#     g.add_edge(b1[i], b2[i])
# for edge in g.get_edges():
#     p1 = edge['from']
#     p2 = edge['to']
#     edge["color"] = 'black'
# g.show('gt_GRN.html')